[versions]
appcompat = "1.7.0"
activity = "1.9.2"
kotlin = "1.8.22"

[libraries]
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
activity = { module = "androidx.activity:activity", version.ref = "activity" }
kotlin = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }

[plugins]
android-application = { id = "com.android.application", version = "8.9.1" }